- name: Disable queue with DelayedJobs (for now )
  template:
    src: "{{ playbook_dir }}/roles/queue/templates/delayed_job_config.rb"
    dest: "{{ release_dir }}/config/initializers/delayed_job_config.rb"
